### ISSUE TITLE
reading ~/.zshrc fails

### ISSUE THREAD

**Issue by zyper86** [Sharktheone/arch-mojo#11]
When running the script, it fails to read ~/.zshrc.

Traceback (most recent call last):
  File "/home/zyper/.cache/yay/mojo-git/src/install.py", line 187, in <module>
    shell_rc = open(rc_pth, "r").read()
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xab in position 10263: invalid start byte

Because (my) .zshrc is an ISO-8859 text file, which is not compatible with utf-8, hence the error. 
However, writing still works, so I suggest removing the line, as shell_rc isn't used.

**Comment by Sharktheone** [comment]
Thanks for the issue! I must have completely missed that one when I was rebuilding the script.
In the case, the script doesn't find any shell-rc file, gives the option to skip adding the modular bin folder and the library folder to the path. Probably I should give the option to also do that when it find one.

I hope, I can fix this soon™, because I don't have much time to spend on this project at the moment.

**Comment by Sharktheone** [comment]
Should be fixed now. I've remove the line that were causing problems plus gave the option to not do shell-rc things.
